name = "crate-client"
prefix = "crate_client"
mainprefix = "synixe"

[version]
git_hash = 0

[hemtt.signing]
authority = "synixe_crate"

[asc]
exclude = [
    "/XEH_preInit.sqf",
]

[hemtt.launch.default]
file_patching = false
parameters = [
    "-connect=arma.synixe.contractors",
    "-port=2602",
    "-password=equals"
]
workshop = [
    "synixe:@3den_attributes_fast_load",
    "synixe:@3denenhanced",
    "synixe:@ace",
    "synixe:@ace_noactionmenu",
    "synixe:@ace_nocrosshair",
    "synixe:@ace_nouniformrestrictions",
    "synixe:@ace_particles",
    "synixe:@ace_realisticdispersion",
    "synixe:@ace_tracers",
    "synixe:@acre2",
    "synixe:@aegis",
    "synixe:@aegis_atlas",
    "synixe:@aegis_opposing_forces",
    "synixe:@aid",
    "synixe:@bozcaada",
    "synixe:@cba_a3",
    "synixe:@cba_rf",
    "synixe:@cba_ws",
    "synixe:@cup_terrains_core",
    "synixe:@cup_terrains_maps",
    "synixe:@edenobjects",
    "synixe:@em",
    "synixe:@emr",
    "synixe:@extendedfortificationsmod",
    "synixe:@generic_civilian_clothing",
    "synixe:@gorkas",
    "synixe:@grad_civs",
    "synixe:@grad_slinghelmet",
    "synixe:@grad_trenches",
    "synixe:@jca_m72a7",
    "synixe:@jca_mp5a5",
    "synixe:@jca_ump45",
    "synixe:@lambs",
    "synixe:@lambs_danger",
    "synixe:@lambs_suppression",
    "synixe:@live_radio",
    "synixe:@low_visibility_attir",
    "synixe:@melb",
    "synixe:@mk13secondary",
    "synixe:@modular_shoothouse",
    "synixe:@modular_warehouse",
    "synixe:@mu",
    "synixe:@open_in_vscode",
    "synixe:@oteden",
    "synixe:@rf",
    "synixe:@sai",
    "synixe:@sma_optics",
    "synixe:@snapping",
    "synixe:@synixe_armoury",
    "synixe:@synixe_equipment",
    "synixe:@synixe_factions",
    "synixe:@synixe_hider",
    "synixe:@synixe_mgp",
    "synixe:@synixe_mod",
    "synixe:@synixe_pictures",
    "synixe:@synixe_standardization",
    "synixe:@theseus_services",
    "synixe:@toh_characters",
    "synixe:@urikimissionitems",
    "synixe:@vet_unflipping",
    "synixe:@ws",
    "synixe:@zec",
    "synixe:@zeic",
    "synixe:@zen",
    "synixe:@zis",
]
