name = "crate-client"
prefix = "crate_client"
mainprefix = "synixe"

[version]
git_hash = 0

[hemtt.signing]
authority = "synixe_crate"

[asc]
exclude = [
    "/XEH_preInit.sqf",
]

[hemtt.launch.default]
workshop = [
    "synixe:@cba_a3",
    "synixe:@ace",
    "synixe:@zen",
    "synixe:@acre2",
]
